.TH SOPHOS 1
.SH NAME
sophos - a socket server sharing wisdom
.SH SYNOPSIS
.B sophos
.RB [-p\ port]
.RB [-f\ file]
.SH DESCRIPTION
sophos loads wisdoms line by line from a given file. Randomly shares one wisdom
per connected client using a socket listening on given port.
.SH OPTIONS
.TP
.B \-p port
Specify the port for the socket.
.TP
.B \-f file
Specify the file containing wisdoms.
.SH BUGS
Report issues to GitHub repository: https://github.com/keveri/sophos/issues
.SH AUTHOR
Matias Keveri
